xen: Add missing include to hvm_op.h
hvm_op.h uses domain_t but does not include the header which contains the
typedef:

  include/xen/interface/hvm/hvm_op.h:29:5: error: unknown type name 'domid_t'

Fixes: 28447ea41542 ("xen: Move xen_setup_callback_vector() definition to include/xen/hvm.h")
Reported-by : kbuild test robot <lkp@intel.com>
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>