kbuild: make module name conflict a warning again
The module name conflict is still remaining.

  error: the following would cause module name conflict:
    drivers/char/adi.ko
    drivers/input/joystick/adi.ko

Make it a warning again to build sparc64 allmodconfig successfully.

Fixes: 8451791d1ff0 ("kbuild: make module name conflict fatal error")
Reported-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>