mm-mempolicy-support-memory-hotplug-in-weighted-interleave-checkpatch-fixes
ERROR: space required before the open parenthesis '('
#178: FILE: mm/mempolicy.c:3570:
+	switch(action) {

total: 1 errors, 0 warnings, 163 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/mm-mempolicy-support-memory-hotplug-in-weighted-interleave.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Rakie Kim <rakie.kim@sk.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>