x86/xen: Unbreak hypervisor callback on 32bit
The IDTENTRY conversion broke XEN on 32bit:

ld: arch/x86/xen/setup.o: in function `register_callback':                                                                                                                                                                                                                     
>> arch/x86/xen/setup.c:940: undefined reference to `xen_asm_exc_xen_hypervisor_callback'

The reason is that 32bit does not have the extra indirection of 64bit via
the XEN trampolines and 32bit never emitted an actual IDT entry function
for this.

 - Add and use IDTENTRY_XENCB so the ASM variant emits an entry point only
   for 64 bit.

 - Rename the 32bit ASM function to match the 64bit trampoline function name.

Fixup a few comments as well.

Fixes: 66a07b44e765 ("x86/entry: Switch XEN/PV hypercall entry to IDTENTRY")
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
Cc: Juergen Gross <jgross@suse.com>